CREATE TYPE "jour_semaine" AS ENUM (
  'lundi',
  'mardi',
  'mercredi',
  'jeudi',
  'vendredi',
  'samedi',
  'dimanche'
);

CREATE TABLE "ressource" (
  "label" varchar PRIMARY KEY,
  "description" text
);

CREATE TABLE "jour_horaire" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jour" jour_semaine NOT NULL,
  "debut" time NOT NULL,
  "fin" time NOT NULL,
  "label" varchar
);

CREATE TABLE "reservation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar NOT NULL,
  "prenom" varchar NOT NULL,
  "numero_tel" varchar NOT NULL,
  "date_reservation" timestamp NOT NULL
);

CREATE TABLE "reservations_client_resource" (
  "id" integer PRIMARY KEY,
  "reservation" integer NOT NULL,
  "resource" varchar NOT NULL,
  "jour_horaire" jour_semaine NOT NULL,
  "heure" time NOT NULL
);

ALTER TABLE "jour_horaire" ADD FOREIGN KEY ("label") REFERENCES "ressource" ("label");

ALTER TABLE "reservations_client_resource" ADD FOREIGN KEY ("reservation") REFERENCES "reservation" ("id");

ALTER TABLE "reservations_client_resource" ADD FOREIGN KEY ("resource") REFERENCES "ressource" ("label");
